<template>
  <BaseTableDragScroll
    :tableHeaders="tableHeaders"
    :tableItems="tableItems"
    :tableActions="tableActions"
    :messageActionMore="messageActionMore"
  ></BaseTableDragScroll>
</template>
<script>
import BaseTableDragScroll from '@/components/commonApp/BaseTableDragScroll.vue'

export default {
  components: { BaseTableDragScroll },
  layout: 'empty',
  data() {
    return {
      key: 0,
      keyHeader: 0,
      isOpen: false,
      tableActions: {
        edit: true,
        delete: true,
      },
      messageActionMore: {
        title: {
          title_delete: '該当のユーザーを削除してよろしいですか？',
          title_rel: 'Has Relation',
        },
        submit: 'OK',
        cancel: 'キャンセル',
      },
      tableHeaders: [
        {
          label: '#',
          value: 'id',
          width: 80,
          minWidth: 60,
          align: 'center',
          isFilter: true,
        },
        {
          label: '契約者名',
          value: 'customer_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: '拠点名',
          value: 'area_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: '工場/ビル名',
          value: 'building_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: '住所',
          value: 'building_address',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: 'システム容量（kW）',
          value: 'system_capacity',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: 'EPC事業者',
          value: 'epc_company_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: 'EPC事業者住所',
          value: 'epc_company_address',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: '施工業者',
          value: 'construction_company_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: '施工業者住所',
          value: 'construction_company_address',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: 'メンテナンス事業者',
          value: 'maintenance_company_name',
          width: 200,
          minWidth: 60,
          align: 'left',
          isFilter: true,
        },
        {
          label: 'メンテナンス事業者住所',
          value: 'maintenance_company_address',
          align: 'left',
          isFilter: true,
        },
      ],
      tableItems: [
        {
          id: 10,
          solar_panel_group_id: 'S0000010',
          customer_id: 1,
          area_name: 'サンシャインパーク久礼',
          building_name: 'all',
          building_address: '〒789-1301 高知県高岡郡中土佐町久礼3022-1',
          system_capacity: 569,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 8,
          solar_panel_group_id: 'S0000008',
          customer_id: 1,
          area_name: 'サンシャインパーク佐川',
          building_name: 'サブ変電所1エリア',
          building_address:
            '〒789-1204 高知県高岡郡佐川町加茂 字板家ノ上1811他',
          system_capacity: 1881,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 17,
          solar_panel_group_id: 'S0000017',
          customer_id: 1,
          area_name: 'サンシャインパーク佐川',
          building_name: 'サブ変電所2エリア',
          building_address:
            '〒789-1204 高知県高岡郡佐川町加茂 字板家ノ上1811他',
          system_capacity: 2508,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 18,
          solar_panel_group_id: 'S0000018',
          customer_id: 1,
          area_name: 'サンシャインパーク佐川',
          building_name: 'サブ変電所3エリア',
          building_address:
            '〒789-1204 高知県高岡郡佐川町加茂 字板家ノ上1811他',
          system_capacity: 2508,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 19,
          solar_panel_group_id: 'S0000019',
          customer_id: 1,
          area_name: 'サンシャインパーク佐川',
          building_name: 'サブ変電所4エリア',
          building_address:
            '〒789-1204 高知県高岡郡佐川町加茂 字板家ノ上1811他',
          system_capacity: 2508,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 20,
          solar_panel_group_id: 'S0000020',
          customer_id: 1,
          area_name: 'サンシャインパーク佐川',
          building_name: 'サブ変電所5エリア',
          building_address:
            '〒789-1204 高知県高岡郡佐川町加茂 字板家ノ上1811他',
          system_capacity: 2508,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 22,
          solar_panel_group_id: 'S0000022',
          customer_id: 1,
          area_name: 'サンシャインパーク加茂',
          building_name: 'all',
          building_address: '〒762-0023 香川県坂出市加茂町1620-1他',
          system_capacity: 1371,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 1,
          solar_panel_group_id: 'S0000001',
          customer_id: 1,
          area_name: 'サンシャインパーク北条',
          building_name: 'サブ変電所1エリア',
          building_address: '〒799-2431 愛媛県松山市北条1055',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 2,
          solar_panel_group_id: 'S0000002',
          customer_id: 1,
          area_name: 'サンシャインパーク北条',
          building_name: 'サブ変電所2エリア',
          building_address: '〒799-2431 愛媛県松山市北条1055',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 3,
          solar_panel_group_id: 'S0000003',
          customer_id: 1,
          area_name: 'サンシャインパーク北条',
          building_name: 'サブ変電所3エリア',
          building_address: '〒799-2431 愛媛県松山市北条1055',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 4,
          solar_panel_group_id: 'S0000004',
          customer_id: 1,
          area_name: 'サンシャインパーク北条',
          building_name: 'サブ変電所4エリア',
          building_address: '〒799-2431 愛媛県松山市北条1055',
          system_capacity: 1869,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 9,
          solar_panel_group_id: 'S0000009',
          customer_id: 1,
          area_name: 'サンシャインパーク大屋冨',
          building_name: 'all',
          building_address: '〒762-0015 香川県坂出市大屋冨町3100-43',
          system_capacity: 1008,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 11,
          solar_panel_group_id: 'S0000011',
          customer_id: 1,
          area_name: 'サンシャインパーク箸蔵',
          building_name: 'all',
          building_address: '〒778-0020 徳島県三好市池田町州津藤ノ井409-2他',
          system_capacity: 336,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 12,
          solar_panel_group_id: 'S0000012',
          customer_id: 1,
          area_name: 'サンシャインパーク豊浜',
          building_name: 'サブ変電所2エリア',
          building_address: '〒769-1601 香川県観音寺市豊浜町姫浜 字新屋敷325-1',
          system_capacity: 1246,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 13,
          solar_panel_group_id: 'S0000013',
          customer_id: 1,
          area_name: 'サンシャインパーク豊浜',
          building_name: 'サブ変電所3エリア',
          building_address: '〒769-1601 香川県観音寺市豊浜町姫浜 字新屋敷325-1',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 14,
          solar_panel_group_id: 'S0000014',
          customer_id: 1,
          area_name: 'サンシャインパーク豊浜',
          building_name: 'サブ変電所4エリア',
          building_address: '〒769-1601 香川県観音寺市豊浜町姫浜 字新屋敷325-1',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 15,
          solar_panel_group_id: 'S0000015',
          customer_id: 1,
          area_name: 'サンシャインパーク豊浜',
          building_name: 'サブ変電所5エリア',
          building_address: '〒769-1601 香川県観音寺市豊浜町姫浜 字新屋敷325-1',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 16,
          solar_panel_group_id: 'S0000016',
          customer_id: 1,
          area_name: 'サンシャインパーク豊浜',
          building_name: 'サブ変電所6エリア',
          building_address: '〒769-1601 香川県観音寺市豊浜町姫浜 字新屋敷325-1',
          system_capacity: 2492,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
        {
          id: 21,
          solar_panel_group_id: 'S0000021',
          customer_id: 1,
          area_name: 'もみの木サンシャインパーク',
          building_name: 'all',
          building_address:
            '〒769-0319 香川県仲多度都まんのう町追上 字願袖392-1他',
          system_capacity: 2380,
          epc_company_name: '',
          epc_company_address: '',
          construction_company_name: '',
          construction_company_address: '',
          maintenance_company_name: '',
          maintenance_company_address: '',
          customer: {
            id: 1,
            customer_id: 'C0000001',
            name: '株式会社四電工',
            address: '香川県高松市花ノ宮町2-3-9',
          },
        },
      ],
    }
  },
}
</script>
